//! Resource model (`Start.md` §9.4).
//!
//! A `Resource` is any on-disk (or in-database) artifact an agent leaves
//! behind. Resources are the unit of *space attribution* and the input to
//! cleanup unit formation (§9.5, Phase 6). Providers report facts about
//! resources; they never classify risk.

use crate::provider::ProviderId;
use crate::size::SizeInfo;
use serde::{Deserialize, Serialize};

/// Stable identifier of one resource within a provider.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ResourceId(pub String);

impl ResourceId {
    pub fn new(id: impl Into<String>) -> Self {
        Self(id.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Reference to a resource (id + kind), used in dependency edges and
/// session→resource links. Keeping it small avoids cycles when full
/// `Resource` structs reference each other.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ResourceRef {
    pub id: ResourceId,
    pub kind: ResourceKind,
}

/// What a resource *is* semantically (`Start.md` §9.4).
///
/// Kind drives policy (§11.3: logs/caches/checkpoints get resource-specific
/// rules) and UI grouping. `Unknown` is fail-closed for cleanup.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum ResourceKind {
    /// Session transcript and its sidecars (the session's own files).
    Session,
    /// Agent default workspace / user-chosen working directory (Blocked).
    Workspace,
    /// Project-level metadata (e.g. Claude Code `memory/`).
    ProjectMetadata,
    /// Subagent transcript nested inside a parent session.
    Subagent,
    /// Files generated by agent runs (outputs, artifacts).
    GeneratedFile,
    /// Regenerable cache data.
    Cache,
    /// Logs (append-only, may have audit value).
    Log,
    /// Checkpoints / file-history snapshots (enable `/rewind`-style restore).
    Checkpoint,
    /// SQLite database or index referencing other resources.
    Database,
    /// Structure not understood — fail closed.
    Unknown,
}

/// Exclusive vs shared ownership of a resource (`Start.md` §9.4).
///
/// `Shared` includes content-addressed stores with no verified back-refs
/// (WorkBuddy `blobs/`, Claude Code `file-history/`). Shared/Unknown
/// resources can never form an executable cleanup unit (red line #6/#4).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Ownership {
    Exclusive,
    Shared,
    Unknown,
}

/// Who manages (writes) the resource.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ManagedBy {
    /// The agent product owns this path.
    Agent,
    /// AgentTidy created it (future: operation logs).
    AgentTidy,
    /// User content — never cleanable, only reportable.
    User,
}

/// Where the resource physically lives.
///
/// One resource has exactly one locator: file-system paths are the common
/// case; `DatabaseRecord` covers index rows that must be kept consistent
/// with their files (Codex `threads` rows, WorkBuddy `sessions` rows) —
/// such resources are never independently deletable (red line #8).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "kebab-case")]
pub enum ResourceLocator {
    /// A single file.
    File { path: String },
    /// A directory treated as one resource.
    Dir { path: String },
    /// A set of files forming one logical resource (e.g. a session's
    /// transcript + sidecar files; atomic unit pre-image, §9.5).
    FileSet { paths: Vec<String> },
    /// A row/record inside an agent database.
    DatabaseRecord { database: String, record_id: String },
}

/// A discovered agent resource (read-only analysis view).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Resource {
    pub id: ResourceId,
    pub provider: ProviderId,
    /// Installation this resource was scanned from.
    pub installation_id: String,
    pub kind: ResourceKind,
    /// Physical location (files or DB record).
    pub locator: ResourceLocator,
    pub ownership: Ownership,
    pub managed_by: ManagedBy,
    pub size: SizeInfo,
    /// Owning session (when the resource is session-scoped).
    pub session_id: Option<crate::session::SessionId>,
    /// Owning project, when known.
    pub project: Option<crate::session::ProjectRef>,
    pub created_at: Option<u64>,
    pub updated_at: Option<u64>,
    /// Resources this one depends on (e.g. transcript → DB index row).
    pub dependencies: Vec<ResourceRef>,
    /// Provider-specific facts. Facts only — never policy conclusions.
    pub metadata: serde_json::Map<String, serde_json::Value>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn locator_serde_roundtrip() {
        let loc = ResourceLocator::FileSet {
            paths: vec!["/x/02e8.jsonl".into(), "/x/02e8.meta.json".into()],
        };
        let json = serde_json::to_string(&loc).unwrap();
        assert!(json.contains(r#""type":"file-set""#));
        let back: ResourceLocator = serde_json::from_str(&json).unwrap();
        assert_eq!(back, loc);
    }

    #[test]
    fn kind_serde_is_kebab_case() {
        let json = serde_json::to_string(&ResourceKind::ProjectMetadata).unwrap();
        assert_eq!(json, r#""project-metadata""#);
    }
}
